seed: 42
data:
  tile: 512
  overlap: 64
  polarization: "VV"
  normalize: "zscore"
  sampler:
    train_tiles: 3000
    val_tiles: 400
    test_tiles: 400
model:
  encoder: "resnet18"
  segmenter: "unet"
  loss: "dice_bce"
  lr: 1e-3
  epochs: 10
  batch_size: 16
eval:
  metrics: ["iou", "f1", "precision", "recall", "brier", "ece"]
  slices:
    - "backscatter_intensity_quantiles"
    - "slope_bins"
    - "landcover_class"
calibration:
  method: "temperature"
  val_split: 0.2
serve:
  threshold: 0.45
  max_tile_batch: 32
policy:
  export_geojson: true
  keep_crs: true
