name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: docker build -t drshym_climate:ci -f docker/Dockerfile .

      # Optional demo inference if you include small test data + checkpoint in repo
      # - name: Demo inference (optional)
      #   if: ${{ hashFiles('data/scenes/**/*.tif') != '' && hashFiles('artifacts/checkpoints/**') != '' }}
      #   run: |
      #     python scripts/export_stitched.py \
      #       --proba_dir outputs/tiles \
      #       --scene_meta data/scenes/meta.json \
      #       --out outputs/scenes

      - name: Ensure outputs/ exists (placeholder)
        run: |
          mkdir -p outputs
          if [ ! -e outputs/README.txt ]; then
            echo "CI placeholder. Real results appear here when inference runs." > outputs/README.txt
          fi

      - name: Upload artifacts/
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload outputs/
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            outputs/**
          if-no-files-found: ignore
          retention-days: 7
