name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi uvicorn pydantic numpy scipy matplotlib pyyaml torch torchvision rasterio shapely pyproj
      - name: Run tests
        run: pytest -q
      - name: Build Docker image
        run: docker build -t drshym_climate:ci -f docker/Dockerfile .
